language: php

php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-source

script:
  - "vendor/bin/phpcs" --standard=./build/config/phpcs.ruleset.xml
  - "vendor/bin/phpunit" -c ./build/config/phpunit.xml

after_success:
  - cd build/output
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
